; ASCII
	charmap "\t", $09
	charmap "\n", $0A
	charmap "\r", $0D
	charmap " ", $20
	charmap "!", $21
	charmap "\"", $22
	charmap "#", $23
	charmap "$", $24
	charmap "%", $25
	charmap "&", $26
	charmap "'", $27
	charmap "(", $28
	charmap ")", $29
	charmap "*", $2A
	charmap "+", $2B
	charmap ",", $2C
	charmap "-", $2D
	charmap ".", $2E
	charmap "/", $2F
	charmap "0", $30
	charmap "1", $31
	charmap "2", $32
	charmap "3", $33
	charmap "4", $34
	charmap "5", $35
	charmap "6", $36
	charmap "7", $37
	charmap "8", $38
	charmap "9", $39
	charmap ":", $3A
	charmap ";", $3B
	charmap "<", $3C
	charmap "=", $3D
	charmap ">", $3E
	charmap "?", $3F
	charmap "@", $40
	charmap "A", $41
	charmap "B", $42
	charmap "C", $43
	charmap "D", $44
	charmap "E", $45
	charmap "F", $46
	charmap "G", $47
	charmap "H", $48
	charmap "I", $49
	charmap "J", $4A
	charmap "K", $4B
	charmap "L", $4C
	charmap "M", $4D
	charmap "N", $4E
	charmap "O", $4F
	charmap "P", $50
	charmap "Q", $51
	charmap "R", $52
	charmap "S", $53
	charmap "T", $54
	charmap "U", $55
	charmap "V", $56
	charmap "W", $57
	charmap "X", $58
	charmap "Y", $59
	charmap "Z", $5A
	charmap "[", $5B
	charmap "\\", $5C
	charmap "]", $5D
	charmap "^", $5E
	charmap "_", $5F
	charmap "`", $60
	charmap "a", $61
	charmap "b", $62
	charmap "c", $63
	charmap "d", $64
	charmap "e", $65
	charmap "f", $66
	charmap "g", $67
	charmap "h", $68
	charmap "i", $69
	charmap "j", $6A
	charmap "k", $6B
	charmap "l", $6C
	charmap "m", $6D
	charmap "n", $6E
	charmap "o", $6F
	charmap "p", $70
	charmap "q", $71
	charmap "r", $72
	charmap "s", $73
	charmap "t", $74
	charmap "u", $75
	charmap "v", $76
	charmap "w", $77
	charmap "x", $78
	charmap "y", $79
	charmap "z", $7A
	charmap "\{", $7B
	charmap "|", $7C
	charmap "}", $7D
	charmap "~", $7E
; selection of CP-1252
	charmap "€", $80
	charmap "‚", $2C ; same tile
	charmap "„", $84
	charmap "…", $85
	charmap "Š", $8A
	charmap "‹", $8B
	charmap "Œ", $8C
	charmap "Ž", $8E
	charmap "‘", $91
	charmap "’", $27 ; same tile
	charmap "“", $93
	charmap "”", $94
	charmap "•", $95
	charmap "–", $2D ; same tile
	charmap "—", $2D ; same tile
	charmap "˜", $7E ; same tile
	charmap "™", $99
	charmap "š", $9A
	charmap "›", $9B
	charmap "œ", $9C
	charmap "ž", $9E
	charmap "Ÿ", $9F
	charmap "¡", $A1
	charmap "¢", $A2
	charmap "£", $A3
	charmap "¤", $A4
	charmap "¥", $A5
	charmap "¦", $A6
	charmap "§", $A7
	charmap "©", $A9
	charmap "ª", $AA
	charmap "«", $AB
	charmap "¬", $AC
	charmap "®", $AE
	charmap "¯", $AF
	charmap "°", $B0
	charmap "±", $B1
	charmap "²", $B2
	charmap "³", $B3
	charmap "µ", $B5
	charmap "¶", $B6
	charmap "·", $B7
	charmap "¹", $B9
	charmap "º", $B0 ; same tile
	charmap "»", $BB
	charmap "¿", $BF
	charmap "À", $C0
	charmap "Á", $C1
	charmap "Â", $C2
	charmap "Ã", $C3
	charmap "Ä", $C4
	charmap "Å", $C5
	charmap "Æ", $C6
	charmap "Ç", $C7
	charmap "È", $C8
	charmap "É", $C9
	charmap "Ê", $CA
	charmap "Ë", $CB
	charmap "Ì", $CC
	charmap "Í", $CD
	charmap "Î", $CE
	charmap "Ï", $CF
	charmap "Ð", $D0
	charmap "Ñ", $D1
	charmap "Ò", $D2
	charmap "Ó", $D3
	charmap "Ô", $D4
	charmap "Õ", $D5
	charmap "Ö", $D6
	charmap "×", $D7
	charmap "Ø", $D8
	charmap "Ù", $D9
	charmap "Ú", $DA
	charmap "Û", $DB
	charmap "Ü", $DC
	charmap "Ý", $DD
	charmap "Þ", $DE
	charmap "ß", $DF
	charmap "à", $E0
	charmap "á", $E1
	charmap "â", $E2
	charmap "ã", $E3
	charmap "ä", $E4
	charmap "å", $E5
	charmap "æ", $E6
	charmap "ç", $E7
	charmap "è", $E8
	charmap "é", $E9
	charmap "ê", $EA
	charmap "ë", $EB
	charmap "ì", $EC
	charmap "í", $ED
	charmap "î", $EE
	charmap "ï", $EF
	charmap "ð", $F0
	charmap "ñ", $F1
	charmap "ò", $F2
	charmap "ó", $F3
	charmap "ô", $F4
	charmap "õ", $F5
	charmap "ö", $F6
	charmap "÷", $F7
	charmap "ø", $F8
	charmap "ù", $F9
	charmap "ú", $FA
	charmap "û", $FB
	charmap "ü", $FC
	charmap "ý", $FD
	charmap "þ", $FE
	charmap "ÿ", $FF
; Extra chars
	charmap "■", $7F
	charmap "■", $81
	charmap "■", $82
	charmap "■", $83
	charmap "■", $86
	charmap "■", $87
	charmap "■", $88
	charmap "■", $89
	charmap "■", $8D
	charmap "■", $8F
	charmap "■", $90
	charmap "■", $92
	charmap "■", $96
	charmap "■", $97
	charmap "■", $98
	charmap "■", $9D
	charmap "■", $A0
	charmap "■", $A8
	charmap "■", $AD
	charmap "■", $B4
	charmap "■", $B8
	charmap "■", $BA
	charmap "■", $BC
	charmap "■", $BD
	charmap "■", $BE
